[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sign_language_rewards = "AELiTsxMv5D4W8bwJA4YvpsrGAc8wvcbskn7Cnsmec86"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
